name: clarity
description: A personal student life OS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.14
  fl_chart: ^0.65.0
  flutter_animate: ^4.2.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
